/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditRequest {
  'id' : string,
  'websiteOrMapsUrl' : string,
  'name' : [] | [string],
  'createdAt' : Time,
  'phoneNumber' : [] | [string],
}
export interface ContactMessage {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
}
export interface DemoRequest {
  'id' : string,
  'status' : string,
  'expiresAt' : Time,
  'createdAt' : Time,
  'businessName' : string,
  'businessType' : string,
  'language' : string,
  'message' : [] | [string],
  'previewSlug' : string,
  'phoneNumber' : string,
}
export interface SiteSettings {
  'basicPrice' : bigint,
  'analyticsId' : string,
  'workingHours' : string,
  'heroSubheadline' : string,
  'businessPrice' : bigint,
  'heroHeadline' : string,
  'advancedPrice' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'extendPreviewExpiry' : ActorMethod<[string, bigint], undefined>,
  'getAllAuditRequests' : ActorMethod<[], Array<AuditRequest>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllDemoRequests' : ActorMethod<[], Array<DemoRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPreviewBySlug' : ActorMethod<[string], [] | [DemoRequest]>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAuditRequest' : ActorMethod<
    [string, [] | [string], [] | [string]],
    undefined
  >,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'submitDemoRequest' : ActorMethod<
    [string, string, string, string, [] | [string]],
    string
  >,
  'updateDemoRequestStatus' : ActorMethod<[string, string], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];