/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AuditRequest = IDL.Record({
  'id' : IDL.Text,
  'websiteOrMapsUrl' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const DemoRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'expiresAt' : Time,
  'createdAt' : Time,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'language' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'previewSlug' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SiteSettings = IDL.Record({
  'basicPrice' : IDL.Nat,
  'analyticsId' : IDL.Text,
  'workingHours' : IDL.Text,
  'heroSubheadline' : IDL.Text,
  'businessPrice' : IDL.Nat,
  'heroHeadline' : IDL.Text,
  'advancedPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'extendPreviewExpiry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllAuditRequests' : IDL.Func([], [IDL.Vec(AuditRequest)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPreviewBySlug' : IDL.Func([IDL.Text], [IDL.Opt(DemoRequest)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAuditRequest' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitDemoRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'updateDemoRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AuditRequest = IDL.Record({
    'id' : IDL.Text,
    'websiteOrMapsUrl' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const DemoRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'expiresAt' : Time,
    'createdAt' : Time,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'language' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'previewSlug' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SiteSettings = IDL.Record({
    'basicPrice' : IDL.Nat,
    'analyticsId' : IDL.Text,
    'workingHours' : IDL.Text,
    'heroSubheadline' : IDL.Text,
    'businessPrice' : IDL.Nat,
    'heroHeadline' : IDL.Text,
    'advancedPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'extendPreviewExpiry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllAuditRequests' : IDL.Func([], [IDL.Vec(AuditRequest)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPreviewBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DemoRequest)],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAuditRequest' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitDemoRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'updateDemoRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };