/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AuditRequest = IDL.Record({
  'id' : IDL.Text,
  'websiteOrMapsUrl' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const DemoRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'expiresAt' : Time,
  'createdAt' : Time,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'language' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'previewSlug' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const PaymentOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'appLink' : IDL.Text,
  'createdAt' : Time,
  'clientPhone' : IDL.Text,
  'utrNumber' : IDL.Text,
  'amount' : IDL.Nat,
  'planName' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : Time,
  'businessType' : IDL.Text,
  'description' : IDL.Text,
  'liveUrl' : IDL.Text,
  'pages' : IDL.Vec(IDL.Text),
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'text' : IDL.Text,
  'businessType' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PaymentOrderStatus = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'appLink' : IDL.Text,
  'createdAt' : Time,
  'amount' : IDL.Nat,
  'planName' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'googleReviewCount' : IDL.Text,
  'googleRating' : IDL.Text,
  'basicPrice' : IDL.Nat,
  'analyticsId' : IDL.Text,
  'googleBusinessUrl' : IDL.Text,
  'workingHours' : IDL.Text,
  'heroSubheadline' : IDL.Text,
  'businessPrice' : IDL.Nat,
  'heroHeadline' : IDL.Text,
  'advancedPrice' : IDL.Nat,
});
export const UpiSettings = IDL.Record({
  'upiName' : IDL.Text,
  'upiId' : IDL.Text,
  'paymentsEnabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPortfolioItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePortfolioItem' : IDL.Func([IDL.Text], [], []),
  'extendPreviewExpiry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllAuditRequests' : IDL.Func([], [IDL.Vec(AuditRequest)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
  'getAllPaymentOrders' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentOrderStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentOrderStatus)],
      ['query'],
    ),
  'getPreviewBySlug' : IDL.Func([IDL.Text], [IDL.Opt(DemoRequest)], ['query']),
  'getPublicPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUpiSettings' : IDL.Func([], [UpiSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAuditRequest' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitDemoRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'submitPaymentOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Text],
      [],
    ),
  'submitTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateDemoRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePaymentOrderStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePortfolioItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  'updateTestimonialStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateUpiSettings' : IDL.Func([UpiSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AuditRequest = IDL.Record({
    'id' : IDL.Text,
    'websiteOrMapsUrl' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const DemoRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'expiresAt' : Time,
    'createdAt' : Time,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'language' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'previewSlug' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const PaymentOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'appLink' : IDL.Text,
    'createdAt' : Time,
    'clientPhone' : IDL.Text,
    'utrNumber' : IDL.Text,
    'amount' : IDL.Nat,
    'planName' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : Time,
    'businessType' : IDL.Text,
    'description' : IDL.Text,
    'liveUrl' : IDL.Text,
    'pages' : IDL.Vec(IDL.Text),
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'text' : IDL.Text,
    'businessType' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PaymentOrderStatus = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'appLink' : IDL.Text,
    'createdAt' : Time,
    'amount' : IDL.Nat,
    'planName' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'googleReviewCount' : IDL.Text,
    'googleRating' : IDL.Text,
    'basicPrice' : IDL.Nat,
    'analyticsId' : IDL.Text,
    'googleBusinessUrl' : IDL.Text,
    'workingHours' : IDL.Text,
    'heroSubheadline' : IDL.Text,
    'businessPrice' : IDL.Nat,
    'heroHeadline' : IDL.Text,
    'advancedPrice' : IDL.Nat,
  });
  const UpiSettings = IDL.Record({
    'upiName' : IDL.Text,
    'upiId' : IDL.Text,
    'paymentsEnabled' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPortfolioItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePortfolioItem' : IDL.Func([IDL.Text], [], []),
    'extendPreviewExpiry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllAuditRequests' : IDL.Func([], [IDL.Vec(AuditRequest)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllDemoRequests' : IDL.Func([], [IDL.Vec(DemoRequest)], ['query']),
    'getAllPaymentOrders' : IDL.Func([], [IDL.Vec(PaymentOrder)], ['query']),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getApprovedTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentOrderStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentOrderStatus)],
        ['query'],
      ),
    'getPreviewBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DemoRequest)],
        ['query'],
      ),
    'getPublicPortfolioItems' : IDL.Func(
        [],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUpiSettings' : IDL.Func([], [UpiSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAuditRequest' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitDemoRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'submitPaymentOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Text],
        [],
      ),
    'submitTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateDemoRequestStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePaymentOrderStatus' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePortfolioItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
    'updateTestimonialStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateUpiSettings' : IDL.Func([UpiSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };